[pytest]
pythonpath = .

testpaths =
    mobile/tests
    api_tests/tests
    event_tests/tests

python_files = test_*.py

addopts =
    -v
    --alluredir=allure-results
    --html=reports/report.html
    --self-contained-html

markers =
    mobile: pruebas de la app movil
    api: pruebas de servicios API
    events: pruebas de la capa de eventos/telemetria (Kafka)
