import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")

GPS_RAW_EVENTS_TOPIC = os.getenv("GPS_RAW_EVENTS_TOPIC", "gps-raw-events")

PRODUCE_TIMEOUT_SECONDS = float(os.getenv("EVENTS_PRODUCE_TIMEOUT", "10"))
CONSUME_TIMEOUT_SECONDS = float(os.getenv("EVENTS_CONSUME_TIMEOUT", "15"))

MAX_EVENT_LATENCY_SECONDS = float(os.getenv("EVENTS_MAX_LATENCY", "2.0"))

KAFKA_SECURITY_PROTOCOL = os.getenv("KAFKA_SECURITY_PROTOCOL")
KAFKA_SASL_MECHANISM = os.getenv("KAFKA_SASL_MECHANISM")
KAFKA_SASL_USERNAME = os.getenv("KAFKA_SASL_USERNAME")
KAFKA_SASL_PASSWORD = os.getenv("KAFKA_SASL_PASSWORD")
